CREATE TABLE wods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    type VARCHAR(20) NOT NULL,
    date DATE NOT NULL,
    approved BOOLEAN NOT NULL
);

CREATE TABLE results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    wod_id BIGINT NOT NULL,
    result VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_results_wod FOREIGN KEY (wod_id) REFERENCES wods(id) ON DELETE CASCADE
);

CREATE TABLE wod_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_wods_date ON wods(date);
CREATE INDEX idx_results_user_id ON results(user_id);
CREATE INDEX idx_results_wod_id ON results(wod_id);
CREATE INDEX idx_proposals_status ON wod_proposals(status);
