CREATE TABLE personal_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    exercise VARCHAR(40) NOT NULL,
    weight NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_personal_records_user_exercise ON personal_records(user_id, exercise);
CREATE INDEX idx_personal_records_created_at ON personal_records(created_at);
